name: relic

on:
  schedule:
  - cron: "0 2 * * *"
  push:
    branches: [ master ]

jobs:

  run:
    name: Email randomly selected Pinboard links
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run
      env:
        PINBOARD_API_TOKEN: ${{ secrets.PINBOARD_API_TOKEN }}
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        FROM_ADDRESS: ${{ secrets.FROM_ADDRESS }}
        TO_ADDRESS: ${{ secrets.TO_ADDRESS }}
      run: go run cmd/main.go
